/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author stevedownes
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ExitDBBT = new javax.swing.JButton();
        pnlMainMenu = new javax.swing.JPanel();
        pnlGrid = new javax.swing.JPanel();
        KaryawanBT = new javax.swing.JButton();
        AbsensiBT = new javax.swing.JButton();
        PayrollBT = new javax.swing.JButton();
        RotasiBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2026-06-02 at 11.45.28.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel1);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Selamat datang, user!");
        pnlHeader.add(jLabel2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel2);

        ExitDBBT.setBackground(new java.awt.Color(255, 255, 255));
        ExitDBBT.setForeground(new java.awt.Color(255, 255, 255));
        ExitDBBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Screenshot_20260603_082214.png"))); // NOI18N
        ExitDBBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        ExitDBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitDBBTActionPerformed(evt);
            }
        });
        pnlHeader.add(ExitDBBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlMainMenu.setBackground(new java.awt.Color(240, 240, 240));
        pnlMainMenu.setLayout(new java.awt.GridBagLayout());

        pnlGrid.setBackground(new java.awt.Color(240, 240, 240));
        pnlGrid.setMaximumSize(new java.awt.Dimension(1000, 500));
        pnlGrid.setMinimumSize(new java.awt.Dimension(1000, 500));
        pnlGrid.setName(""); // NOI18N
        pnlGrid.setPreferredSize(new java.awt.Dimension(1000, 500));
        pnlGrid.setLayout(new java.awt.GridLayout(2, 2, 25, 25));

        KaryawanBT.setBackground(new java.awt.Color(255, 255, 255));
        KaryawanBT.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        KaryawanBT.setForeground(new java.awt.Color(0, 0, 0));
        KaryawanBT.setText("Karyawan");
        KaryawanBT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        KaryawanBT.setBorderPainted(false);
        KaryawanBT.setPreferredSize(new java.awt.Dimension(450, 225));
        KaryawanBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KaryawanBTMouseEntered(evt);
            }
        });
        pnlGrid.add(KaryawanBT);

        AbsensiBT.setBackground(new java.awt.Color(255, 255, 255));
        AbsensiBT.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        AbsensiBT.setForeground(new java.awt.Color(0, 0, 0));
        AbsensiBT.setText("Absensi & Cuti");
        AbsensiBT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        AbsensiBT.setPreferredSize(new java.awt.Dimension(450, 225));
        AbsensiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsensiBTActionPerformed(evt);
            }
        });
        pnlGrid.add(AbsensiBT);

        PayrollBT.setBackground(new java.awt.Color(255, 255, 255));
        PayrollBT.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        PayrollBT.setForeground(new java.awt.Color(0, 0, 0));
        PayrollBT.setText("Payroll");
        PayrollBT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        PayrollBT.setPreferredSize(new java.awt.Dimension(450, 225));
        pnlGrid.add(PayrollBT);

        RotasiBT.setBackground(new java.awt.Color(255, 255, 255));
        RotasiBT.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        RotasiBT.setForeground(new java.awt.Color(0, 0, 0));
        RotasiBT.setText("Rotasi Jabatan");
        RotasiBT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        RotasiBT.setPreferredSize(new java.awt.Dimension(450, 225));
        pnlGrid.add(RotasiBT);

        pnlMainMenu.add(pnlGrid, new java.awt.GridBagConstraints());

        getContentPane().add(pnlMainMenu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbsensiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsensiBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbsensiBTActionPerformed

    private void ExitDBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitDBBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitDBBTActionPerformed

    private void KaryawanBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KaryawanBTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_KaryawanBTMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbsensiBT;
    private javax.swing.JButton ExitDBBT;
    private javax.swing.JButton KaryawanBT;
    private javax.swing.JButton PayrollBT;
    private javax.swing.JButton RotasiBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlGrid;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainMenu;
    // End of variables declaration//GEN-END:variables
}
