/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author stevedownes
 */
public class EditData extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditData.class.getName());

    /**
     * Creates new form Dashboard
     */
    public EditData() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackKwnBT = new javax.swing.JButton();
        pnlTempatTabel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LabelJK = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LabelUsia = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelDept = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LabelPosisi = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LabelStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelTipe = new javax.swing.JLabel();
        LabelPosisi3 = new javax.swing.JLabel();
        BatalEditBT = new javax.swing.JButton();
        SimpanEditBT = new javax.swing.JButton();
        StatusCBox = new javax.swing.JComboBox<>();
        TipeCBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        LabelPosisi4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/NamaLogo.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel2);

        BackKwnBT.setBackground(new java.awt.Color(255, 255, 255));
        BackKwnBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitLogo.png"))); // NOI18N
        BackKwnBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        BackKwnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackKwnBTActionPerformed(evt);
            }
        });
        pnlHeader.add(BackKwnBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlTempatTabel.setBackground(new java.awt.Color(240, 240, 240));
        pnlTempatTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        pnlTempatTabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        pnlTempatTabel.setLayout(new javax.swing.BoxLayout(pnlTempatTabel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Jenis Kelamin:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 40));

        LabelJK.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelJK.setForeground(new java.awt.Color(0, 0, 0));
        LabelJK.setText("LabelJK");
        jPanel4.add(LabelJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Usia:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        LabelUsia.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelUsia.setForeground(new java.awt.Color(0, 0, 0));
        LabelUsia.setText("LabelUsia");
        jPanel4.add(LabelUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Departemen:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        LabelDept.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelDept.setForeground(new java.awt.Color(0, 0, 0));
        LabelDept.setText("LabelDept");
        jPanel4.add(LabelDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tipe:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        LabelPosisi.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelPosisi.setForeground(new java.awt.Color(0, 0, 0));
        LabelPosisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/arrow.png"))); // NOI18N
        jPanel4.add(LabelPosisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Status Aktif:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, -1));

        LabelStatus.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelStatus.setForeground(new java.awt.Color(0, 0, 0));
        LabelStatus.setText("LabelStatus");
        jPanel4.add(LabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Lengkap:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        LabelNama.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelNama.setForeground(new java.awt.Color(0, 0, 0));
        LabelNama.setText("LabelNama");
        jPanel4.add(LabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        LabelTipe.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelTipe.setForeground(new java.awt.Color(0, 0, 0));
        LabelTipe.setText("LabelTipe");
        jPanel4.add(LabelTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, -1, -1));

        LabelPosisi3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelPosisi3.setForeground(new java.awt.Color(0, 0, 0));
        LabelPosisi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/arrow.png"))); // NOI18N
        jPanel4.add(LabelPosisi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, -1, -1));

        BatalEditBT.setBackground(new java.awt.Color(255, 255, 255));
        BatalEditBT.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        BatalEditBT.setForeground(new java.awt.Color(0, 0, 0));
        BatalEditBT.setText("Batal");
        BatalEditBT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel4.add(BatalEditBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 750, 170, 40));

        SimpanEditBT.setBackground(new java.awt.Color(0, 0, 0));
        SimpanEditBT.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        SimpanEditBT.setForeground(new java.awt.Color(255, 255, 255));
        SimpanEditBT.setText("Simpan");
        SimpanEditBT.setMaximumSize(new java.awt.Dimension(93, 39));
        SimpanEditBT.setMinimumSize(new java.awt.Dimension(93, 39));
        SimpanEditBT.setPreferredSize(new java.awt.Dimension(93, 39));
        jPanel4.add(SimpanEditBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 750, 170, -1));

        StatusCBox.setBackground(new java.awt.Color(255, 255, 255));
        StatusCBox.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        StatusCBox.setForeground(new java.awt.Color(0, 0, 0));
        StatusCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StatusCBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        StatusCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusCBoxActionPerformed(evt);
            }
        });
        jPanel4.add(StatusCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 650, 360, 50));

        TipeCBox.setBackground(new java.awt.Color(255, 255, 255));
        TipeCBox.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TipeCBox.setForeground(new java.awt.Color(0, 0, 0));
        TipeCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TipeCBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        TipeCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipeCBoxActionPerformed(evt);
            }
        });
        jPanel4.add(TipeCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 560, 360, 50));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Posisi:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        LabelPosisi4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelPosisi4.setForeground(new java.awt.Color(0, 0, 0));
        LabelPosisi4.setText("LabelPosisi");
        jPanel4.add(LabelPosisi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        jPanel3.add(jPanel4);

        pnlTempatTabel.add(jPanel3);

        getContentPane().add(pnlTempatTabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackKwnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackKwnBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackKwnBTActionPerformed

    private void StatusCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusCBoxActionPerformed

    private void TipeCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipeCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipeCBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditData().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackKwnBT;
    private javax.swing.JButton BatalEditBT;
    private javax.swing.JLabel LabelDept;
    private javax.swing.JLabel LabelJK;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelPosisi;
    private javax.swing.JLabel LabelPosisi3;
    private javax.swing.JLabel LabelPosisi4;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelTipe;
    private javax.swing.JLabel LabelUsia;
    private javax.swing.JButton SimpanEditBT;
    private javax.swing.JComboBox<String> StatusCBox;
    private javax.swing.JComboBox<String> TipeCBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTempatTabel;
    // End of variables declaration//GEN-END:variables
}
