/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.KaryawanController;
import Model.Pegawai;
import javax.swing.JOptionPane;

public class InfoLengkap extends javax.swing.JFrame {
    private int idKaryawan;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InfoLengkap.class.getName());

    /**
     * Creates new form Dashboard
     */
    public InfoLengkap() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
    public InfoLengkap(int id) {
        this();
        this.idKaryawan = id;
        muatData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackKwnBT = new javax.swing.JButton();
        pnlTempatTabel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LabelJK = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LabelUsia = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelDept = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LabelPosisi = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LabelStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        HistoriBT = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        LabelGaji = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        LabelCuti = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LabelTipe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/NamaLogo.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel2);

        BackKwnBT.setBackground(new java.awt.Color(255, 255, 255));
        BackKwnBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitLogo.png"))); // NOI18N
        BackKwnBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        BackKwnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackKwnBTActionPerformed(evt);
            }
        });
        pnlHeader.add(BackKwnBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlTempatTabel.setBackground(new java.awt.Color(240, 240, 240));
        pnlTempatTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        pnlTempatTabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        pnlTempatTabel.setLayout(new javax.swing.BoxLayout(pnlTempatTabel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Jenis Kelamin:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 40));

        LabelJK.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelJK.setForeground(new java.awt.Color(0, 0, 0));
        LabelJK.setText("LabelJK");
        jPanel4.add(LabelJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Usia:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        LabelUsia.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelUsia.setForeground(new java.awt.Color(0, 0, 0));
        LabelUsia.setText("LabelUsia");
        jPanel4.add(LabelUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Departemen:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        LabelDept.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelDept.setForeground(new java.awt.Color(0, 0, 0));
        LabelDept.setText("LabelDept");
        jPanel4.add(LabelDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Posisi:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        LabelPosisi.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelPosisi.setForeground(new java.awt.Color(0, 0, 0));
        LabelPosisi.setText("LabelPosisi");
        jPanel4.add(LabelPosisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Status Aktif:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        LabelStatus.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelStatus.setForeground(new java.awt.Color(0, 0, 0));
        LabelStatus.setText("LabelStatus");
        jPanel4.add(LabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Lengkap:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        LabelNama.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelNama.setForeground(new java.awt.Color(0, 0, 0));
        LabelNama.setText("LabelNama");
        jPanel4.add(LabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        HistoriBT.setBackground(new java.awt.Color(255, 255, 255));
        HistoriBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/historyvector.png"))); // NOI18N
        HistoriBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        HistoriBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoriBTActionPerformed(evt);
            }
        });
        jPanel4.add(HistoriBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 60, 60));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Gaji:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        LabelGaji.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelGaji.setForeground(new java.awt.Color(0, 0, 0));
        LabelGaji.setText("LabelGaji");
        jPanel4.add(LabelGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Kuota Cuti:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, -1, -1));

        LabelCuti.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelCuti.setForeground(new java.awt.Color(0, 0, 0));
        LabelCuti.setText("LabelCuti");
        jPanel4.add(LabelCuti, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 770, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Tipe:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        LabelTipe.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        LabelTipe.setForeground(new java.awt.Color(0, 0, 0));
        LabelTipe.setText("LabelTipe");
        jPanel4.add(LabelTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, -1, -1));

        jPanel3.add(jPanel4);

        pnlTempatTabel.add(jPanel3);

        getContentPane().add(pnlTempatTabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void muatData() {
        Pegawai p = KaryawanController.cariKaryawan(idKaryawan);
        if (p != null) {
            LabelNama.setText(p.getNama());
            LabelJK.setText(p.getJenisKelamin());
            LabelUsia.setText(String.valueOf(p.getUsia()));
            LabelDept.setText(p.getDepartemen().getNama());
            LabelPosisi.setText(p.getJabatan().getNama());
            LabelTipe.setText(p.getTipe());
            LabelStatus.setText(p.isStatusAktif() ? "Aktif" : "Nonaktif");
            LabelGaji.setText("Rp " + p.hitungGaji());
            LabelCuti.setText(String.valueOf(p.getKuotaCuti()));
            
        }
    }
    
    private void BackKwnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackKwnBTActionPerformed
        new ManageKaryawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackKwnBTActionPerformed

    private void HistoriBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoriBTActionPerformed
        java.util.List<String> histori = KaryawanController.historiJabatan(idKaryawan);
    
    StringBuilder sb = new StringBuilder();
    if (histori.isEmpty()) {
        sb.append("Belum ada histori jabatan untuk karyawan ini.");
    } else {
        for (String h : histori) {
            sb.append(h).append("\n");
        }
    }
    
    // Tampilkan popup (JOptionPane)
    javax.swing.JOptionPane.showMessageDialog(
        this,                           
        sb.toString(),                  
        "Histori Jabatan",             
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_HistoriBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InfoLengkap().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackKwnBT;
    private javax.swing.JButton HistoriBT;
    private javax.swing.JLabel LabelCuti;
    private javax.swing.JLabel LabelDept;
    private javax.swing.JLabel LabelGaji;
    private javax.swing.JLabel LabelJK;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelPosisi;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelTipe;
    private javax.swing.JLabel LabelUsia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTempatTabel;
    // End of variables declaration//GEN-END:variables
}
