/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.KaryawanController;
import controller.LemburController;
import Model.Pegawai;
import Model.Departemen;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import java.util.List;

public class InputLembur extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputLembur.class.getName());

    /**
     * Creates new form Dashboard
     */
    public InputLembur() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        isiComboKaryawan();
        isiComboDepartemen();
        isiComboLamaLembur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BackKwnBT = new javax.swing.JButton();
        pnlTempatTabel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SimpanLembuBT = new javax.swing.JButton();
        LembuNamaCBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        LembuLamaCBox = new javax.swing.JComboBox<>();
        LembuDeptCBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/NamaLogo.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel2);

        BackKwnBT.setBackground(new java.awt.Color(255, 255, 255));
        BackKwnBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitLogo.png"))); // NOI18N
        BackKwnBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        BackKwnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackKwnBTActionPerformed(evt);
            }
        });
        pnlHeader.add(BackKwnBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlTempatTabel.setBackground(new java.awt.Color(240, 240, 240));
        pnlTempatTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        pnlTempatTabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        pnlTempatTabel.setLayout(new javax.swing.BoxLayout(pnlTempatTabel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Lama Lembur:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Lengkap:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        SimpanLembuBT.setBackground(new java.awt.Color(0, 0, 0));
        SimpanLembuBT.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        SimpanLembuBT.setForeground(new java.awt.Color(255, 255, 255));
        SimpanLembuBT.setText("Simpan");
        SimpanLembuBT.setMaximumSize(new java.awt.Dimension(93, 39));
        SimpanLembuBT.setMinimumSize(new java.awt.Dimension(93, 39));
        SimpanLembuBT.setPreferredSize(new java.awt.Dimension(93, 39));
        SimpanLembuBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanLembuBTActionPerformed(evt);
            }
        });
        jPanel4.add(SimpanLembuBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 170, -1));

        LembuNamaCBox.setBackground(new java.awt.Color(255, 255, 255));
        LembuNamaCBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LembuNamaCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        LembuNamaCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LembuNamaCBoxActionPerformed(evt);
            }
        });
        jPanel4.add(LembuNamaCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 640, 50));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Departemen:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        LembuLamaCBox.setBackground(new java.awt.Color(255, 255, 255));
        LembuLamaCBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LembuLamaCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(LembuLamaCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 640, 50));

        LembuDeptCBox2.setBackground(new java.awt.Color(255, 255, 255));
        LembuDeptCBox2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LembuDeptCBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        LembuDeptCBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LembuDeptCBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(LembuDeptCBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 640, 50));

        jPanel3.add(jPanel4);

        pnlTempatTabel.add(jPanel3);

        getContentPane().add(pnlTempatTabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isiComboKaryawan() {
        LembuNamaCBox.removeAllItems();
        List<Pegawai> karyawanList = KaryawanController.daftarKaryawan();
        for (Pegawai p : karyawanList) {
            LembuNamaCBox.addItem(p.getNama());
        }
    }

    private void isiComboDepartemen() {
        LembuDeptCBox2.removeAllItems();
        List<Departemen> deptList = KaryawanController.daftarDepartemen();
        for (Departemen d : deptList) {
            LembuDeptCBox2.addItem(d.getNama());
        }
    }

    private void isiComboLamaLembur() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (int i = 1; i <= 24; i++) {
            model.addElement(i + " jam");
        }
        LembuLamaCBox.setModel(model);
    }

    private void BackKwnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackKwnBTActionPerformed
        new ManageAbsensi().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackKwnBTActionPerformed

    private void SimpanLembuBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanLembuBTActionPerformed
        String nama = (String) LembuNamaCBox.getSelectedItem();
        String strJam = (String) LembuLamaCBox.getSelectedItem();

        if (nama == null || strJam == null) {
            JOptionPane.showMessageDialog(this, "Pilih karyawan dan lama lembur!");
            return;
        }

        // Input tanggal melalui dialog
        String tanggal = JOptionPane.showInputDialog(this, "Masukkan tanggal lembur (format: yyyy-MM-dd):", "Tanggal Lembur", JOptionPane.QUESTION_MESSAGE);
        if (tanggal == null || tanggal.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal harus diisi!");
            return;
        }

        int jam;
        try {
            jam = Integer.parseInt(strJam.replace(" jam", ""));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jam lembur tidak valid!");
            return;
        }

        Pegawai p = KaryawanController.daftarKaryawan().stream()
                .filter(k -> k.getNama().equals(nama)).findFirst().orElse(null);
        if (p != null) {
            LemburController.tambahLembur(p.getId(), tanggal, jam);
            JOptionPane.showMessageDialog(this, "Lembur berhasil disimpan.");
            new ManageAbsensi().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Karyawan tidak ditemukan!");
        }
    }//GEN-LAST:event_SimpanLembuBTActionPerformed

    private void LembuNamaCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LembuNamaCBoxActionPerformed
        String nama = (String) LembuNamaCBox.getSelectedItem();
        if (nama != null) {
            Pegawai p = KaryawanController.daftarKaryawan().stream()
                    .filter(k -> k.getNama().equals(nama))
                    .findFirst().orElse(null);
            if (p != null) {
                LembuDeptCBox2.setSelectedItem(p.getDepartemen().getNama());
            }
        }
    }//GEN-LAST:event_LembuNamaCBoxActionPerformed

    private void LembuDeptCBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LembuDeptCBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LembuDeptCBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InputLembur().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackKwnBT;
    private javax.swing.JComboBox<String> LembuDeptCBox2;
    private javax.swing.JComboBox<String> LembuLamaCBox;
    private javax.swing.JComboBox<String> LembuNamaCBox;
    private javax.swing.JButton SimpanLembuBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTempatTabel;
    // End of variables declaration//GEN-END:variables
}
