/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AbsenController;
import Model.RekapAbsensi;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class LihatAbsensi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LihatAbsensi.class.getName());

    /**
     * Creates new form Dashboard
     */
    public LihatAbsensi() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        aturTabel();
        muatRekapBulanIni();

        javax.swing.table.JTableHeader header = AbsensiTbl.getTableHeader();

        header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                setBackground(new java.awt.Color(0, 0, 0));
                setForeground(java.awt.Color.WHITE);
                setFont(new java.awt.Font("Roboto", java.awt.Font.BOLD, 14));
                setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                return this;
            }
        });

        header.setPreferredSize(new java.awt.Dimension(header.getPreferredSize().width, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TanggalLB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BackKwnBT = new javax.swing.JButton();
        pnlTempatTabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AbsensiTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/NamaLogo.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel2);

        TanggalLB.setBackground(new java.awt.Color(255, 255, 255));
        TanggalLB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TanggalLB.setForeground(new java.awt.Color(0, 0, 0));
        TanggalLB.setText("jLabel2");
        pnlHeader.add(TanggalLB);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel1);

        BackKwnBT.setBackground(new java.awt.Color(255, 255, 255));
        BackKwnBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitLogo.png"))); // NOI18N
        BackKwnBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        BackKwnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackKwnBTActionPerformed(evt);
            }
        });
        pnlHeader.add(BackKwnBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlTempatTabel.setBackground(new java.awt.Color(240, 240, 240));
        pnlTempatTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        pnlTempatTabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        pnlTempatTabel.setLayout(new javax.swing.BoxLayout(pnlTempatTabel, javax.swing.BoxLayout.LINE_AXIS));

        AbsensiTbl.setBackground(new java.awt.Color(255, 255, 255));
        AbsensiTbl.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        AbsensiTbl.setForeground(new java.awt.Color(44, 62, 80));
        AbsensiTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Departemen", "Posisi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        AbsensiTbl.setGridColor(new java.awt.Color(230, 230, 230));
        AbsensiTbl.setRowHeight(45);
        AbsensiTbl.setShowGrid(true);
        jScrollPane1.setViewportView(AbsensiTbl);
        if (AbsensiTbl.getColumnModel().getColumnCount() > 0) {
            AbsensiTbl.getColumnModel().getColumn(0).setMinWidth(50);
            AbsensiTbl.getColumnModel().getColumn(0).setPreferredWidth(50);
            AbsensiTbl.getColumnModel().getColumn(0).setMaxWidth(50);
            AbsensiTbl.getColumnModel().getColumn(0).setHeaderValue("No");
            AbsensiTbl.getColumnModel().getColumn(1).setHeaderValue("Nama");
            AbsensiTbl.getColumnModel().getColumn(2).setHeaderValue("Departemen");
            AbsensiTbl.getColumnModel().getColumn(3).setHeaderValue("Posisi");
        }

        pnlTempatTabel.add(jScrollPane1);

        getContentPane().add(pnlTempatTabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aturTabel() {
        // Model tabel untuk rekap
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"No", "Nama Karyawan", "Total Hadir", "Tidak Hadir", "Terlambat"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        AbsensiTbl.setModel(model);

        // Lebar kolom nomor
        AbsensiTbl.getColumnModel().getColumn(0).setMinWidth(50);
        AbsensiTbl.getColumnModel().getColumn(0).setPreferredWidth(50);
        AbsensiTbl.getColumnModel().getColumn(0).setMaxWidth(50);

        // Styling header (hitam putih)
        javax.swing.table.JTableHeader header = AbsensiTbl.getTableHeader();
        header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setBackground(new java.awt.Color(0, 0, 0));
                setForeground(java.awt.Color.WHITE);
                setFont(new java.awt.Font("Roboto", java.awt.Font.BOLD, 14));
                setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                return this;
            }
        });
        header.setPreferredSize(new java.awt.Dimension(header.getPreferredSize().width, 40));
    }

    private void muatRekapBulanIni() {
        LocalDate sekarang = LocalDate.now();
        String bulan = sekarang.format(DateTimeFormatter.ofPattern("yyyy-MM"));
        TanggalLB.setText("Rekap Absensi Bulan: " + bulan);

        List<RekapAbsensi> rekapList = AbsenController.rekapPerBulan(bulan);
        DefaultTableModel model = (DefaultTableModel) AbsensiTbl.getModel();
        model.setRowCount(0);
        int no = 1;
        for (RekapAbsensi ra : rekapList) {
            model.addRow(new Object[]{
                no++,
                ra.getNamaKaryawan(),
                ra.getTotalHadir(),
                ra.getTotalTidakHadir(),
                ra.getTotalTerlambat()
            });
        }
    }

    private void BackKwnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackKwnBTActionPerformed
        new PilihAbsensi().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackKwnBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LihatAbsensi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AbsensiTbl;
    private javax.swing.JButton BackKwnBT;
    private javax.swing.JLabel TanggalLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTempatTabel;
    // End of variables declaration//GEN-END:variables
}
