/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author stevedownes
 */
public class ManageAbsensi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageAbsensi.class.getName());

    /**
     * Creates new form Dashboard
     */
    public ManageAbsensi() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        ManageLemburBT.setText("Manage Lembur");
        ManageLemburBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageLemburBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        ManageCutiBT.setText("Manage Cuti");
        ManageCutiBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageCutiBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ExitDBBT = new javax.swing.JButton();
        pnlMainMenu = new javax.swing.JPanel();
        pnlGrid = new javax.swing.JPanel();
        ManageLemburBT = new javax.swing.JButton();
        ManageCutiBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/NamaLogo.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel1);

        ExitDBBT.setBackground(new java.awt.Color(255, 255, 255));
        ExitDBBT.setForeground(new java.awt.Color(255, 255, 255));
        ExitDBBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitLogo.png"))); // NOI18N
        ExitDBBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        ExitDBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitDBBTActionPerformed(evt);
            }
        });
        pnlHeader.add(ExitDBBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlMainMenu.setBackground(new java.awt.Color(240, 240, 240));
        pnlMainMenu.setLayout(new java.awt.GridBagLayout());

        pnlGrid.setBackground(new java.awt.Color(240, 240, 240));
        pnlGrid.setMaximumSize(new java.awt.Dimension(1000, 500));
        pnlGrid.setMinimumSize(new java.awt.Dimension(1000, 500));
        pnlGrid.setName(""); // NOI18N
        pnlGrid.setPreferredSize(new java.awt.Dimension(1000, 500));
        pnlGrid.setLayout(new java.awt.GridLayout(1, 2, 25, 25));

        ManageLemburBT.setBackground(new java.awt.Color(255, 255, 255));
        ManageLemburBT.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        ManageLemburBT.setForeground(new java.awt.Color(0, 0, 0));
        ManageLemburBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/likevector_1.png"))); // NOI18N
        ManageLemburBT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        ManageLemburBT.setBorderPainted(false);
        ManageLemburBT.setPreferredSize(new java.awt.Dimension(450, 225));
        ManageLemburBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageLemburBTMouseEntered(evt);
            }
        });
        ManageLemburBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageLemburBTActionPerformed(evt);
            }
        });
        pnlGrid.add(ManageLemburBT);

        ManageCutiBT.setBackground(new java.awt.Color(255, 255, 255));
        ManageCutiBT.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        ManageCutiBT.setForeground(new java.awt.Color(0, 0, 0));
        ManageCutiBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/dislekvector.png"))); // NOI18N
        ManageCutiBT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        ManageCutiBT.setPreferredSize(new java.awt.Dimension(450, 225));
        ManageCutiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCutiBTActionPerformed(evt);
            }
        });
        pnlGrid.add(ManageCutiBT);

        pnlMainMenu.add(pnlGrid, new java.awt.GridBagConstraints());

        getContentPane().add(pnlMainMenu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageCutiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCutiBTActionPerformed
        new PengajuanCuti().setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageCutiBTActionPerformed

    private void ExitDBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitDBBTActionPerformed
        new PilihAbsensi().setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitDBBTActionPerformed

    private void ManageLemburBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageLemburBTMouseEntered

    }//GEN-LAST:event_ManageLemburBTMouseEntered

    private void ManageLemburBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageLemburBTActionPerformed
        new InputLembur().setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageLemburBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageAbsensi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitDBBT;
    private javax.swing.JButton ManageCutiBT;
    private javax.swing.JButton ManageLemburBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlGrid;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainMenu;
    // End of variables declaration//GEN-END:variables
}
