/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CutiController;
import controller.KaryawanController;
import Model.Cuti;
import Model.Pegawai;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.List;

public class PengajuanCuti extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PengajuanCuti.class.getName());

    /**
     * Creates new form Dashboard
     */
    private JTable tblCuti;
    private DefaultTableModel modelTabel;
    private JButton btnTambahCuti;

    public PengajuanCuti() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        buatTabelCuti();
        muatDataCuti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackKwnBT = new javax.swing.JButton();
        pnlTempatTabel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/NamaLogo.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel2);

        BackKwnBT.setBackground(new java.awt.Color(255, 255, 255));
        BackKwnBT.setForeground(new java.awt.Color(255, 255, 255));
        BackKwnBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitLogo.png"))); // NOI18N
        BackKwnBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        BackKwnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackKwnBTActionPerformed(evt);
            }
        });
        pnlHeader.add(BackKwnBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlTempatTabel.setBackground(new java.awt.Color(240, 240, 240));
        pnlTempatTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        pnlTempatTabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        pnlTempatTabel.setLayout(new javax.swing.BoxLayout(pnlTempatTabel, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setBackground(new java.awt.Color(255, 255, 255));
        jList1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        pnlTempatTabel.add(jScrollPane2);

        getContentPane().add(pnlTempatTabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buatTabelCuti() {
        // Hapus semua komponen lama di pnlTempatTabel
        pnlTempatTabel.removeAll();
        pnlTempatTabel.setLayout(new BorderLayout());

        // Model tabel
        modelTabel = new DefaultTableModel(
                new String[]{"ID", "Nama Karyawan", "Tanggal Mulai", "Tanggal Selesai", "Status", "Aksi"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return col == 5; // kolom aksi bisa diedit
            }
        };
        tblCuti = new JTable(modelTabel);
        // Sembunyikan kolom ID
        tblCuti.getColumnModel().getColumn(0).setMinWidth(0);
        tblCuti.getColumnModel().getColumn(0).setMaxWidth(0);
        tblCuti.getColumnModel().getColumn(0).setWidth(0);
        // Lebar kolom aksi
        tblCuti.getColumnModel().getColumn(5).setMinWidth(150);
        tblCuti.getColumnModel().getColumn(5).setPreferredWidth(150);
        tblCuti.setRowHeight(40);

        // Styling header
        JTableHeader header = tblCuti.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setBackground(Color.BLACK);
                setForeground(Color.WHITE);
                setFont(new Font("Roboto", Font.BOLD, 14));
                setHorizontalAlignment(SwingConstants.CENTER);
                return this;
            }
        });
        header.setPreferredSize(new Dimension(header.getPreferredSize().width, 40));

        // Tombol aksi
        tblCuti.getColumnModel().getColumn(5).setCellRenderer(new TombolRenderer());
        tblCuti.getColumnModel().getColumn(5).setCellEditor(new TombolEditor());

        // Panel bawah untuk tombol tambah cuti
        JPanel panelBawah = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        btnTambahCuti = new JButton("+ Ajukan Cuti");
        btnTambahCuti.setFont(new Font("Roboto", Font.BOLD, 18));
        btnTambahCuti.setBackground(Color.BLACK);
        btnTambahCuti.setForeground(Color.WHITE);
        btnTambahCuti.addActionListener(e -> bukaFormAjuan());
        panelBawah.add(btnTambahCuti);

        pnlTempatTabel.add(new JScrollPane(tblCuti), BorderLayout.CENTER);
        pnlTempatTabel.add(panelBawah, BorderLayout.SOUTH);

        pnlTempatTabel.revalidate();
        pnlTempatTabel.repaint();
    }

    private void muatDataCuti() {
        modelTabel.setRowCount(0);
        List<Cuti> list = CutiController.semuaCuti();
        for (Cuti c : list) {
            if (c.getStatus().equals("Pending")) {
                modelTabel.addRow(new Object[]{
                    c.getId(),
                    c.getKaryawanNama(),
                    c.getTanggalMulai(),
                    c.getTanggalSelesai(),
                    c.getStatus(),
                    "Aksi"
                });
            }
        }
    }

    private void bukaFormAjuan() {
        JComboBox<String> cmbKaryawan = new JComboBox<>();
        for (Pegawai p : KaryawanController.daftarKaryawan()) {
            cmbKaryawan.addItem(p.getNama());
        }
        JTextField txtMulai = new JTextField(10);
        JTextField txtSelesai = new JTextField(10);
        JTextArea txtAlasan = new JTextArea(3, 20);
        JPanel panel = new JPanel(new GridLayout(0, 2, 10, 10));
        panel.add(new JLabel("Karyawan:"));
        panel.add(cmbKaryawan);
        panel.add(new JLabel("Tanggal Mulai (yyyy-MM-dd):"));
        panel.add(txtMulai);
        panel.add(new JLabel("Tanggal Selesai:"));
        panel.add(txtSelesai);
        panel.add(new JLabel("Alasan:"));
        panel.add(new JScrollPane(txtAlasan));

        int result = JOptionPane.showConfirmDialog(this, panel, "Ajukan Cuti", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            String nama = (String) cmbKaryawan.getSelectedItem();
            Pegawai p = KaryawanController.daftarKaryawan().stream()
                    .filter(k -> k.getNama().equals(nama)).findFirst().orElse(null);
            if (p != null) {
                CutiController.ajukanCuti(p.getId(), txtMulai.getText(), txtSelesai.getText(), txtAlasan.getText());
                muatDataCuti();
                JOptionPane.showMessageDialog(this, "Pengajuan cuti berhasil.");
            } else {
                JOptionPane.showMessageDialog(this, "Karyawan tidak ditemukan!");
            }
        }
    }

    // Inner class untuk renderer tombol
    class TombolRenderer extends JPanel implements TableCellRenderer {

        JButton btnSetuju = new JButton("Setuju");
        JButton btnTolak = new JButton("Tolak");

        public TombolRenderer() {
            setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
            setBackground(Color.WHITE);
            btnSetuju.setBackground(new Color(46, 204, 113));
            btnSetuju.setForeground(Color.WHITE);
            btnTolak.setBackground(new Color(231, 76, 60));
            btnTolak.setForeground(Color.WHITE);
            add(btnSetuju);
            add(btnTolak);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {
            return this;
        }
    }

    // Inner class untuk editor tombol
    class TombolEditor extends AbstractCellEditor implements TableCellEditor {

        JPanel panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 5));
        JButton btnSetuju = new JButton("Setuju");
        JButton btnTolak = new JButton("Tolak");
        int row;

        public TombolEditor() {
            panel.setBackground(Color.WHITE);
            btnSetuju.setBackground(new Color(46, 204, 113));
            btnSetuju.setForeground(Color.WHITE);
            btnTolak.setBackground(new Color(231, 76, 60));
            btnTolak.setForeground(Color.WHITE);
            panel.add(btnSetuju);
            panel.add(btnTolak);
            btnSetuju.addActionListener(e -> {
                fireEditingStopped();
                int id = (int) modelTabel.getValueAt(row, 0);
                try {
                    CutiController.setujuiCuti(id);
                    muatDataCuti();
                    JOptionPane.showMessageDialog(tblCuti, "Cuti disetujui. Kuota cuti telah dikurangi.");
                } catch (IllegalStateException ex) {
                    JOptionPane.showMessageDialog(tblCuti, ex.getMessage(), "Gagal", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(tblCuti, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            });
            btnTolak.addActionListener(e -> {
                fireEditingStopped();
                int id = (int) modelTabel.getValueAt(row, 0);
                CutiController.tolakCuti(id);
                muatDataCuti();
                JOptionPane.showMessageDialog(tblCuti, "Cuti ditolak dan dihapus.");
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int col) {
            this.row = row;
            return panel;
        }

        @Override
        public Object getCellEditorValue() {
            return null;
        }
    }


    private void BackKwnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackKwnBTActionPerformed
        new ManageAbsensi().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackKwnBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PengajuanCuti().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackKwnBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTempatTabel;
    // End of variables declaration//GEN-END:variables
}
