/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author stevedownes
 */
import controller.KaryawanController;
import Model.Pegawai;
import Model.Departemen;
import javax.swing.JOptionPane;


public class RotasiJabatan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RotasiJabatan.class.getName());

    /**
     * Creates new form Dashboard
     */
    public RotasiJabatan() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        isiComboDepartemen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackKwnBT = new javax.swing.JButton();
        pnlTempatTabel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CariBT = new javax.swing.JButton();
        TFCariNama = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        CariDeptCBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/NamaLogo.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel2);

        BackKwnBT.setBackground(new java.awt.Color(255, 255, 255));
        BackKwnBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitLogo.png"))); // NOI18N
        BackKwnBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        BackKwnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackKwnBTActionPerformed(evt);
            }
        });
        pnlHeader.add(BackKwnBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlTempatTabel.setBackground(new java.awt.Color(240, 240, 240));
        pnlTempatTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        pnlTempatTabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        pnlTempatTabel.setLayout(new javax.swing.BoxLayout(pnlTempatTabel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Departemen:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Lengkap:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        CariBT.setBackground(new java.awt.Color(0, 0, 0));
        CariBT.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        CariBT.setForeground(new java.awt.Color(255, 255, 255));
        CariBT.setText("Cari");
        CariBT.setMaximumSize(new java.awt.Dimension(93, 39));
        CariBT.setMinimumSize(new java.awt.Dimension(93, 39));
        CariBT.setPreferredSize(new java.awt.Dimension(93, 39));
        CariBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariBTActionPerformed(evt);
            }
        });
        jPanel4.add(CariBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 170, -1));

        TFCariNama.setBackground(new java.awt.Color(255, 255, 255));
        TFCariNama.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jPanel4.add(TFCariNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 640, 50));

        jTextField2.setText("jTextField1");
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 640, 50));

        CariDeptCBox.setBackground(new java.awt.Color(255, 255, 255));
        CariDeptCBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        CariDeptCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(CariDeptCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 640, 50));

        jPanel3.add(jPanel4);

        pnlTempatTabel.add(jPanel3);

        getContentPane().add(pnlTempatTabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isiComboDepartemen() {
        CariDeptCBox.removeAllItems();
        // Tambahkan opsi "Semua Departemen" di awal
        CariDeptCBox.addItem("Semua Departemen");
        for (Departemen d : KaryawanController.daftarDepartemen()) {
            CariDeptCBox.addItem(d.getNama());
        }
    }
    private void BackKwnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackKwnBTActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackKwnBTActionPerformed

    private void CariBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariBTActionPerformed
        String nama = TFCariNama.getText().trim();
        String dept = (String) CariDeptCBox.getSelectedItem();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama karyawan yang ingin dicari!");
            return;
        }
        // Cari karyawan berdasarkan nama (dan departemen jika dipilih selain "Semua Departemen")
        Pegawai p = null;
        if (dept != null && !dept.equals("Semua Departemen")) {
            // Cari berdasarkan nama dan departemen (perlu method khusus, untuk sederhana kita cari nama lalu cocokkan departemen)
            p = KaryawanController.cariKaryawanByNama(nama);
            if (p != null && !p.getDepartemen().getNama().equals(dept)) {
                p = null; // tidak cocok
            }
        } else {
            p = KaryawanController.cariKaryawanByNama(nama);
        }
        if (p != null) {
            new EditJabatan(p.getId()).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Karyawan tidak ditemukan! Periksa nama dan departemen.");
        }
    }//GEN-LAST:event_CariBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new RotasiJabatan().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackKwnBT;
    private javax.swing.JButton CariBT;
    private javax.swing.JComboBox<String> CariDeptCBox;
    private javax.swing.JTextField TFCariNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTempatTabel;
    // End of variables declaration//GEN-END:variables
}
