/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.KaryawanController;
import Model.Pegawai;
import Model.KaryawanTetap;
import Model.Magang;
import Model.Departemen;
import Model.Jabatan;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import java.util.List;


public class TambahKaryawan extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TambahKaryawan.class.getName());

    /**
     * Creates new form Dashboard
     */
    public TambahKaryawan() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        isiCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackKwnBT = new javax.swing.JButton();
        pnlTempatTabel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CariBT = new javax.swing.JButton();
        TFNamaKwn = new javax.swing.JTextField();
        KelaminCBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFUsiaKwn = new javax.swing.JTextField();
        TambahDeptCBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        TambahPosisiCBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        TipeCBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        pnlHeader.setPreferredSize(new java.awt.Dimension(881, 120));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/NamaLogo.jpeg"))); // NOI18N
        pnlHeader.add(jLabel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.add(jPanel2);

        BackKwnBT.setBackground(new java.awt.Color(255, 255, 255));
        BackKwnBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitLogo.png"))); // NOI18N
        BackKwnBT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        BackKwnBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackKwnBTActionPerformed(evt);
            }
        });
        pnlHeader.add(BackKwnBT);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlTempatTabel.setBackground(new java.awt.Color(240, 240, 240));
        pnlTempatTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        pnlTempatTabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        pnlTempatTabel.setLayout(new javax.swing.BoxLayout(pnlTempatTabel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1, 15, 15));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Departemen:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Lengkap:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        CariBT.setBackground(new java.awt.Color(0, 0, 0));
        CariBT.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        CariBT.setForeground(new java.awt.Color(255, 255, 255));
        CariBT.setText("Tambah");
        CariBT.setMaximumSize(new java.awt.Dimension(93, 39));
        CariBT.setMinimumSize(new java.awt.Dimension(93, 39));
        CariBT.setPreferredSize(new java.awt.Dimension(93, 39));
        CariBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariBTActionPerformed(evt);
            }
        });
        jPanel4.add(CariBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 620, 170, -1));

        TFNamaKwn.setBackground(new java.awt.Color(255, 255, 255));
        TFNamaKwn.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jPanel4.add(TFNamaKwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 640, 50));

        KelaminCBox.setBackground(new java.awt.Color(255, 255, 255));
        KelaminCBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        KelaminCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(KelaminCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 640, 50));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jenis Kelamin:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Usia:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        TFUsiaKwn.setBackground(new java.awt.Color(255, 255, 255));
        TFUsiaKwn.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jPanel4.add(TFUsiaKwn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 80, 50));

        TambahDeptCBox.setBackground(new java.awt.Color(255, 255, 255));
        TambahDeptCBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TambahDeptCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(TambahDeptCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 640, 50));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Posisi:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        TambahPosisiCBox.setBackground(new java.awt.Color(255, 255, 255));
        TambahPosisiCBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TambahPosisiCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(TambahPosisiCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 640, 50));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tipe:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        TipeCBox.setBackground(new java.awt.Color(255, 255, 255));
        TipeCBox.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TipeCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Karyawan tetap", "Magang" }));
        jPanel4.add(TipeCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 640, 50));

        jPanel3.add(jPanel4);

        pnlTempatTabel.add(jPanel3);

        getContentPane().add(pnlTempatTabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isiCombo() {
        // Jenis Kelamin
        KelaminCBox.setModel(new DefaultComboBoxModel<>(new String[]{"L", "P"}));

        // Tipe Karyawan
        TipeCBox.setModel(new DefaultComboBoxModel<>(new String[]{"Tetap", "Magang"}));

        // Departemen
        List<Departemen> deptList = KaryawanController.daftarDepartemen();
        TambahDeptCBox.removeAllItems();
        for (Departemen d : deptList) {
            TambahDeptCBox.addItem(d.getNama());
        }

        // Posisi
        List<Jabatan> jabList = KaryawanController.daftarJabatan();
        TambahPosisiCBox.removeAllItems();
        for (Jabatan j : jabList) {
            TambahPosisiCBox.addItem(j.getNama());
        }
    }

    private void BackKwnBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackKwnBTActionPerformed
        new ManageKaryawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackKwnBTActionPerformed

    private void CariBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariBTActionPerformed
        String nama = TFNamaKwn.getText().trim();
        String strUsia = TFUsiaKwn.getText().trim();
        String jenisKelamin = (String) KelaminCBox.getSelectedItem();
        String deptNama = (String) TambahDeptCBox.getSelectedItem();
        String posisiNama = (String) TambahPosisiCBox.getSelectedItem();
        String tipe = (String) TipeCBox.getSelectedItem();

        // Validasi sederhana
        if (nama.isEmpty() || strUsia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama dan Usia harus diisi!");
            return;
        }
        int usia;
        try {
            usia = Integer.parseInt(strUsia);
            if (usia <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Usia harus angka positif!");
            return;
        }

        // Cari objek Departemen dan Jabatan berdasarkan nama
        Departemen dept = KaryawanController.daftarDepartemen().stream()
                .filter(d -> d.getNama().equals(deptNama)).findFirst().orElse(null);
        Jabatan jab = KaryawanController.daftarJabatan().stream()
                .filter(j -> j.getNama().equals(posisiNama)).findFirst().orElse(null);

        if (dept == null || jab == null) {
            JOptionPane.showMessageDialog(this, "Data departemen atau posisi tidak valid!");
            return;
        }

        Pegawai pegawai;
        if (tipe.equals("Tetap")) {
            KaryawanTetap kt = new KaryawanTetap();
            // Minta input gaji pokok dan tunjangan via dialog
            String gajiStr = JOptionPane.showInputDialog(this, "Masukkan Gaji Pokok:", "5000000");
            String tunjanganStr = JOptionPane.showInputDialog(this, "Masukkan Tunjangan:", "500000");
            double gajiPokok, tunjangan;
            try {
                gajiPokok = Double.parseDouble(gajiStr);
                tunjangan = Double.parseDouble(tunjanganStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Gaji dan tunjangan harus angka!");
                return;
            }
            kt.setGajiPokok(gajiPokok);
            kt.setTunjangan(tunjangan);
            pegawai = kt;
        } else { // Magang
            Magang m = new Magang();
            String uangHarianStr = JOptionPane.showInputDialog(this, "Masukkan Uang Harian:", "100000");
            String hariKerjaStr = JOptionPane.showInputDialog(this, "Masukkan Jumlah Hari Kerja per Bulan:", "20");
            double uangHarian;
            int hariKerja;
            try {
                uangHarian = Double.parseDouble(uangHarianStr);
                hariKerja = Integer.parseInt(hariKerjaStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Uang harian dan hari kerja harus angka!");
                return;
            }
            m.setUangHarian(uangHarian);
            m.setHariKerja(hariKerja);
            pegawai = m;
        }

        pegawai.setNama(nama);
        pegawai.setUsia(usia);
        pegawai.setJenisKelamin(jenisKelamin);
        pegawai.setDepartemen(dept);
        pegawai.setJabatan(jab);
        pegawai.setTipe(tipe);
        pegawai.setStatusAktif(true);
        pegawai.setKuotaCuti(12);

        // Simpan ke database
        KaryawanController.tambahKaryawan(pegawai);
        JOptionPane.showMessageDialog(this, "Karyawan berhasil ditambahkan!");
        new ManageKaryawan().setVisible(true);
        dispose();
    
    }//GEN-LAST:event_CariBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new TambahKaryawan().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackKwnBT;
    private javax.swing.JButton CariBT;
    private javax.swing.JComboBox<String> KelaminCBox;
    private javax.swing.JTextField TFNamaKwn;
    private javax.swing.JTextField TFUsiaKwn;
    private javax.swing.JComboBox<String> TambahDeptCBox;
    private javax.swing.JComboBox<String> TambahPosisiCBox;
    private javax.swing.JComboBox<String> TipeCBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTempatTabel;
    // End of variables declaration//GEN-END:variables
}
